class SWITCH:
    START = 20

class SERVO_START:
    SERVO_PIN = 21
    START_ANGLE = 2.5
    STOP_ANGLE = 7.0

class SERVO_SIGNAL_1:
    SERVO_PIN = 16
    LEFT = 12 
    RIGHT = 3 
    STRAIGH = 7.5 
    STRAIGH_LEFT = 5
    STRAIGH_RIGHT = 10

class SERVO_SIGNAL_2:
    SERVO_PIN = 12
    LEFT = 12 
    RIGHT = 3
    STRAIGH = 7.5
    STRAIGH_LEFT = 5
    STRAIGH_RIGHT = 10
